### ISSUE TITLE
Stop WebServer

### ISSUE THREAD

**Issue by SkyWar-design** [jchristn/WatsonWebserver#1] opened 2017-04-09 05:03 UTC
Hello, thank you for your work!
How can i stop webserver ?

**Comment by jchristn** [comment] 2017-04-09 15:50
Hi!  Thank you for the suggestion. I'll implement IDisposable on this in the next few days!

Sent with thumbs, please pardon brevity, spelling, and grammar

**Comment by jchristn** [comment] 2017-04-10 00:58
Hi @SkyWar-design , I just committed v1.1.4 and pushed an update to NuGet.  This one has IDisposable implemented so you can either use ```using (var s = ...``` or you can manually call ```s.Dispose()```.  Please let me know if any issues!

**Comment by AChmieletzki** [comment] 2017-08-10 08:49
I don't think the `Dispose()` method is working as intended, after disposing the Server I can still reach it as well as all its routes.

**Comment by jchristn** [comment] 2017-08-10 20:38
Hi @AChmieletzki thank you for this, I will test it again and report back.  Cheers

**Comment by jchristn** [comment] 2017-08-10 20:52
Thanks, was able to reproduce.  Working on this now.

**Comment by jchristn** [comment] 2017-08-10 21:15
Hi @AChmieletzki I just pushed a new version to Git (https://github.com/jchristn/WatsonWebserver/commit/60adc700d226055a6bc442becd833a82aeb66ea7) and also updated NuGet to v1.2.5 with the fix.  The TestDefault project now has a console menu to allow you to call/test .Dispose().  It is working now.  Thank you for catching this.  Closing now, please re-open if the problem persists!

**Closed by jchristn** 2017-08-10 21:15 UTC
